language: node_js
node_js:  
  - 'node'

jobs:
  include:
    - stage: install
      script: npm install
    - stage: build
      script: npm run build
    - stage: coverage
      script: 
        - npm run test-coverage
        - npm run coveralls
    - stage: push
      before_script:
        - npm run build
        - chmod +x scripts/push.sh
      script: 
        - . ./scripts/push.sh
    - stage: deploy-npm
      install:
        - npm install
      script: 
        - npm run build
      deploy:
        provider: npm
        email: ENV_EMAIL
        branch: master
        api_key: ENV_NPM_API_KEY

stages:
  - name: install
    if: (branch != test-push)
  - name: build
    if: (branch != test-push)
  - name: coverage
    if: (branch != test-push)
  - name: push
    if: (branch = test-push)
  - name: deploy-npm
    if: (branch = master) AND (type = push)
