language: node_js
node_js:  
  - 'node'
cache: npm
branches:
  only:
  - master
  - next
  
jobs:
  include:
    - stage: install
      script: npm install
    - stage: build
      script: npm run build
    - stage: coverage
      script: 
        - npm run test-coverage
        - npm run coveralls
    - stage: validate-version
      before_script:
        - chmod +x scripts/validate-version.sh
      script:
        - node scripts/validate-version.js 
    - stage: push
      before_script:
        - npm run build
        - chmod +x scripts/push.sh
      script: 
        - . ./scripts/push.sh
    - stage: deploy-npm
      install:
        - npm install
      script: 
        - npm run build
      deploy:
        provider: npm
        email: $ENV_EMAIL
        branch: master
        api_key: $ENV_NPM_API_KEY
    - stage: deploy-github-releases
      before_script:
        - npm run build
        - chmod +x scripts/prep-github-release.sh
      script: 
        - . ./scripts/prep-github-release.sh
      deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file: "./temp/operationkit.zip"
        skip_cleanup: true
        on:
          tags: true

stages:
  - name: validate-version
    if: (branch = master)
  - name: install
  - name: build
  - name: coverage
  - name: push
    if: (branch = master) AND (type = push)
  - name: deploy-npm
    if: (branch = master) AND (type = push)
  - name: deploy-github-releases
    if: (branch = master) AND (type = push)
