language: node_js
node_js:  
  - 'node'

jobs:
  include:
    - stage: install
      script: npm install
    - stage: build
      script: npm run build
    - stage: push
      script: ./scripts/push.sh
    - stage: coverage
      script: 
        - npm run test-coverage
        - npm run coveralls
    - stage: deploy-npm
      deploy:
        provider: npm
        email: ENV_EMAIL
        branch: master
        api_key: ENV_NPM_API_KEY

script:
  - npm install
  - npm run build

stages:
  - coverage

after_success:
  - name: push
    if: (branch = master) AND (type = push)
  - name: deploy-npm
    if: (branch = master OR branch = next)